language: objective-c

branches:
  only:
    - master

xcode_workspace: AFSignedHTTPRequestOperationManager.xcworkspace
xcode_project: AFSignedHTTPRequestOperationManager.xcodeproj
xcode_scheme: AFSignedHTTPRequestOperationManagerTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild test -workspace "AFSignedHTTPRequestOperationManager.xcworkspace" -scheme AFSignedHTTPRequestOperationManagerTests -destination "platform=iOS Simulator,name=iPhone 6s"
